# Generated by Django 5.0.6 on 2024-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(max_length=64)),
                ('height', models.CharField(max_length=64)),
                ('weight', models.CharField(max_length=64)),
                ('injured', models.BooleanField()),
                ('photo', models.CharField(max_length=64)),
                ('teamid', models.IntegerField()),
                ('teamname', models.CharField(max_length=64)),
                ('teamlogo', models.CharField(max_length=64)),
                ('leagueseason', models.IntegerField()),
                ('g_apps', models.IntegerField(null=True)),
                ('g_starts', models.IntegerField(null=True)),
                ('g_minutes', models.IntegerField(null=True)),
                ('g_position', models.CharField(max_length=64, null=True)),
                ('g_rating', models.CharField(max_length=64, null=True)),
                ('shotstotal', models.IntegerField(null=True)),
                ('shotsontarget', models.IntegerField(null=True)),
                ('goals', models.IntegerField(null=True)),
                ('goalsconceded', models.IntegerField(null=True)),
                ('savesmade', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('passestotal', models.IntegerField(null=True)),
                ('passeskey', models.IntegerField(null=True)),
                ('tackles', models.IntegerField(null=True)),
                ('blocks', models.IntegerField(null=True)),
                ('interceptions', models.IntegerField(null=True)),
                ('duelstotal', models.IntegerField(null=True)),
                ('duelswon', models.IntegerField(null=True)),
                ('dribblesattempted', models.IntegerField(null=True)),
                ('dribblessuccess', models.IntegerField(null=True)),
                ('foulsagainst', models.IntegerField(null=True)),
                ('foulscommitted', models.IntegerField(null=True)),
                ('cardsyellow', models.IntegerField(null=True)),
                ('cardsred', models.IntegerField(null=True)),
                ('cardsyellowred', models.IntegerField(null=True)),
                ('penaltieswon', models.IntegerField(null=True)),
                ('penaltiesconceded', models.IntegerField(null=True)),
                ('penaltiesscored', models.IntegerField(null=True)),
                ('penaltiesmissed', models.IntegerField(null=True)),
                ('penaltiessaved', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
