# Generated by Django 5.0.6 on 2024-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_player_remove_employee_department_delete_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
