# Generated by Django 5.0.6 on 2024-07-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
